### ISSUE TITLE
Add factory for customized functionalities

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#517]
## Subject of the feature

As mentioned in #496, we would like to enable users to use custom data loader, loss, and model without modifying the source code of DeepReg.

A good example is https://github.com/ray-project/ray/blob/master/rllib/examples/custom_keras_model.py#L100 and we need to investigate how this can be done and integrated into DeepReg.

This would probably require
- Code refactoring.
- New features and corresponding tests.
- Documentation update and minimal demo code.

This will be done in multiple PRs regarding:
- backbone: local/global/unet
- model method: ddf/dvf/etc
- loss: dice/ce/etc
- data_aug: affine/ddf/etc

and docs will need to be updated regarding custom model/loss/etc.

**Comment by mathpluscode** [comment]
We can have `ModelCatalog`, `LossCatalog`, `DataLoader`, following similar design here:

https://github.com/ray-project/ray/blob/00ef1179c012719a17c147a5c3b36d6bdbe97195/rllib/models/catalog.py#L96

https://github.com/ray-project/ray/blob/00ef1179c012719a17c147a5c3b36d6bdbe97195/python/ray/tune/registry.py#L108

**Comment by mathpluscode** [comment]
Maybe the example here is more relevant: https://realpython.com/factory-method-python/
The idea would be
- If no changes from the user, we will create a default object like `ModelCatalog`
- The users can initialize the `ModelCatalog` themselves, and register a new model so that the corresponding configs will be recognized.

**Comment by mathpluscode** [comment]
The changes I'm bringing are mainly:
1. Maintain a catalog of known models, backbones or losses etc.
2. Allow user to register his/her own model etc.
3. Use a more general config making things easier.

Regarding the config,
what we have now are:

```yaml
train:
  # define neural network structure
  model:
    method: "ddf" # options include "ddf", "dvf", "conditional" and "affine"
    backbone: "local" # options include "local", "unet" and "global" - use "global" when method=="affine"
    local:
      num_channel_initial: 1 # number of initial channel in local net, controls the size of the network
      extract_levels: [0, 1, 2, 3, 4] # this defines the resolution levels used to compose the output ddf, e.g. one does not use the highest resolution level can be specified as [0,1,2,3]
    unet:
      num_channel_initial: 1 # number of initial channel in u-net, controls the size of the network
      depth: 2 # depth of u-net, the input is at depth = 0, and the bottom is at depth = depth
      pooling: true # for downsampling, use non-parameterized pooling if true, otherwise use conv3d
      concat_skip: false #　when upsampling, concatenate skipped tensor if true, otherwise use addition
```

I'm now simplifying it to (not final version, but wont be far)

```yaml
train:
  # define neural network structure
  model:
    method: "ddf" # options include "ddf", "dvf", "conditional" and "affine"
    backbone:
      name: "local" # options include "local", "unet" and "global" - use "global" when method=="affine"
      num_channel_initial: 1 # number of initial channel in local net, controls the size of the network
      extract_levels: [0, 1, 2, 3, 4] # this defines the resolution levels used to compose the output ddf, e.g. one does not use the highest resolution level can be specified as [0,1,2,3]
```

More detailed docs will need to be provided for each backbone class so that the user knows which configs should be provided.
