### ISSUE TITLE
Refactor optimizer config

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#647]
## Subject of the issue

We should support all optimizers under `tf.keras.optimizers`, therefore, we can use `getattr()` to get rid of `if/else`, e.g.

```python
name = "Adam"
optimizer_cls = getattr(tf.keras.optimizers, name)
```

The corresponding configs can also be simplified, requiring
- a key `"name"` which value should match the optimizer class name, case sensitive.
- other arguments required for the optimizer class, such as `learning_rate`.

For instance, the optimizer config should be

```yaml
optimizer:
    name: "Adam"
    learning_rate: 1.0e-5
```

instead of currently

```yaml
optimizer:
    name: "adam"
    adam:
      learning_rate: 1.0e-5
```

Be aware that, we do not use registry here as for now we do not consider supporting optimizers not under `tf.keras.optimizers`.

## TODO

- code change
- config docs update
- v011 back compatibility support
